#!/bin/sh

set_time="$(date +'%d-%m-%Y_%H:%M')"
release_file=/etc/os-release
logfile=/var/log/${set_time}_updater.log
errorlog=/var/log/${set_time}_updater_errors.log

check_exit_status() {
    if [ $? -ne 0 ]
    then
        echo "An error ocurred, please check the $errorlog file."
    else
        echo "Your system has been sucessfully updated, check $logfile for details"
    fi
}

if grep -q "Arch" $release_file
then
    #the host is based ond Arch, run the pacman update command
    sudo pacman -Syu 1>>$logfile 2>>$errorlog
    check_exit_status
fi

if grep -q "Debian" $release_file || grep -q "Ubuntu" $release_file
then
    #the host is based on Ubuntu or Debian,
    #run the apt version of the command
    sudo apt update 1>>$logfile 2>>$errorlog
    check_exit_status

    sudo apt dist-upgrade -y 1>>$logfile 2>>$errorlog
    check_exit_status
fi
